using System;
using System.Collections.Generic;
using System.Text;

namespace IBGapValue.Resouces
{
    public class LocationCodes
    {
        public static List<string> ListLocationCode = new List<string>()
        {
            "STK.US","STK.US.MAJOR","STK.NYSE","STK.AMEX","STK.ARCA","STK.NASDAQ","STK.NASDAQ.NMS","STK.NASDAQ.SCM","STK.BATS","STK.US.MINOR","STK.PINK","STK.OTCBB","STK.NA","STK.NA.CANADA","STK.NA.TSE","STK.NA.VENTURE","STK.NA.MEXI","STK.EU","STK.EU.VSE","STK.EU.SBF","STK.EU.IBIS","STK.EU.IBIS-XETRA","STK.EU.IBIS-EUSTARS","STK.EU.IBIS-USSTARS","STK.EU.IBIS-ETF","STK.EU.IBIS-NEWX","STK.EU.BVME","STK.EU.AEB","STK.EU.BM","STK.EU.SFB","STK.EU.EBS","STK.EU.LSE","STK.EU.OTHER","STK.EU.PRA","STK.EU.CPH","STK.EU.HEX","STK.EU.OSE","STK.EU.BVL","STK.EU.MOEX","STK.ME","STK.ME.TASE","STK.HK","STK.HK.TSE_JPN","STK.HK.SEHK","STK.HK.SEHKNTL","STK.HK.SEHKSTAR","STK.HK.SEHKSZSE","STK.HK.ASX","STK.HK.NSE","STK.HK.SGX",
            "ETF.EQ.US","ETF.EQ.US.MAJOR","ETF.EQ.ARCA","ETF.EQ.NASDAQ.NMS","ETF.EQ.BATS","ETF.FI.US","ETF.FI.US.MAJOR","ETF.FI.ARCA","ETF.FI.NASDAQ.NMS","ETF.FI.BATS",
            "FUT.US","FUT.GLOBEX","FUT.ECBOT","FUT.IPE","FUT.ENDEX","FUT.NYBOT","FUT.NYMEX","FUT.NYSELIFFE","FUT.CFE","FUT.CFECRYPTO","FUT.CMECRYPTO","FUT.ICECRYPTO","FUT.NA","FUT.NA.CDE","FUT.NA.MEXDER","FUT.EU","FUT.EU.BELFOX","FUT.EU.EUREX","FUT.EU.FTA","FUT.EU.IDEM","FUT.EU.UK","FUT.EU.ICEEU","FUT.EU.LMEOTC","FUT.EU.MEFFRV","FUT.EU.MONEP","FUT.EU.OMS","FUT.HK","FUT.HK.HKFE","FUT.HK.KSE","FUT.HK.NSE","FUT.HK.OSE_JPN","FUT.HK.SGX","FUT.HK.SNFE",
            "IND.US","IND.EU","IND.EU.BELFOX","IND.EU.EUREX","IND.EU.FTA","IND.EU.ICEEU","IND.EU.MONEP","IND.HK","IND.HK.HKFE","IND.HK.KSE","IND.HK.NSE","IND.HK.OSE_JPN","IND.HK.SGX","IND.HK.SNFE",
            "SSF.NA","SSF.NA.MEXDER","SSF.EU","SSF.EU.EUREX","SSF.EU.IDEM","SSF.EU.ICEEU","SSF.EU.MEFFRV","SSF.EU.OMS","SSF.HK","SSF.HK.HKFE","SSF.HK.KSE","SSF.HK.NSE","SSF.HK.SGX",
            "BOND.WW","BOND.US","BOND.EU.EURONEXT","BOND.CD.US","BOND.AGNCY.US","BOND.GOVT.US","BOND.MUNI.US","BOND.GOVT.NON-US","BOND.GOVT.US.NON-US","BOND.GOVT.EU.EURONEXT","BOND.GOVT.HK.SEHK",
            "NATCOMB","NATCOMB.OPT.US","NATCOMB.OPT.AMEX","NATCOMB.OPT.CBOE","NATCOMB.OPT.ISE","NATCOMB.OPT.PHLX","NATCOMB.OPT.PSE","NATCOMB.GLOBEX"
        };
    }
}